### ISSUE TITLE
I have 0.5.2 and it still does not work

### ISSUE THREAD

**Issue by TeardownFan** [Thomasims/TeardownUMF#11]
How

**Comment by TeardownFan** [comment]
Can anyone help me?

**Comment by berwil-1** [comment]
#9 do you still have this problem?
As it states that the file data\ui\menu.lua is not found you should make sure that you run the hook_modloader.bat inside of your Teardown install folder (the same place where you have teardown.exe) cause otherwise, it will not work.

If you encounter more issues you can dm me on Discord if that's possible (CoolJWB#5847).

**Comment by TeardownFan** [comment]
So I have to place it in data?

**Comment by TeardownFan** [comment]
I give up. It's **IMPOSSIBLE** for me to run it. Everytime I try it says an error. I. Give. Up.
